# Generated by Django 5.0 on 2025-02-22 21:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('ref', models.CharField(default=uuid.UUID('4eb1b4b9-8f24-47e1-bf01-d82ccf17b78d'), editable=False, max_length=50, verbose_name='Référence')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Message')),
                ('subject', models.CharField(max_length=250, verbose_name='Sujet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créer le')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ref', models.CharField(default=uuid.UUID('1c72369e-2480-4087-bd35-7320b81ee5c2'), editable=False, max_length=50, verbose_name='Référence')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
